### PR TITLE
Update zec_qt_wallet_de.ts

### PR DESCRIPTION
**Pull request by DenioD**
Add german language

### CODE REVIEW

**Comment by gilardh** [comment]
@DenioD Thank you for your work.

Can you replace all text '<translation type="unfinished">' by '<translation> ?

Example :
Replace '<translation type="unfinished">Betrag</translation>'
by '<translation>Betrag</translation>'

**Comment by DenioD** [comment]
sure

**Comment by DenioD** [comment]
done

**Comment by gilardh** [comment]
Perfect.

**Comment by leto** [comment]
@DenioD just saw this, thank you!! 👍

**Pull request merged**
